package derekpeirce.objectionmaker

import kotlin.time.milliseconds
import kotlin.time.seconds

fun main() {
    makeTrial(defaultTextSpeed = 1) {
        Judge().stand.say("Now that you've defeated the archmage and his cohorts, what would you like to do?")
        Phoenix().stand.say("I'm going to search the room for any hidden treasure.")
        VonKarma().stand.say("I'll follow and keep an eye out for any remaining threats.")
        Maya().stand.say("I'll stay back, but you can take Polly with you! She'll help in your search!")
        Judge().positive.say("Very well. Phoenix, you may make an Investigation check, with advantage from the familiar's Help.")
        Judge().stand.say("Von Karma, with your passive Perception, you can tell that there are no more threats about you.")
        Phoenix().stand.say("Great! I rolled a 12, which comes out to a 24 with modifiers, so")
        VonKarma().snapFinger.holdIt("While Phoenix is busy investigating, I'll take out my dagger and stab him in the back!")
        Phoenix().damage.say("Wait, what? Why would you attack me? And why now?")
        VonKarma().confident.say("Simple. You and Maya took significant damage in the last fight," +
                " and this is my perfect chance for me to finally get rid of both of you and claim the glory for myself.")
        Maya().angry.say("No way! DM, you can't let him do this!")
        VonKarma().armsCrossed.objection("No, this isn't for him to decide. This is what my character would do. DM, allow this fight!")
        Judge().surprised.say("Well, he has a point. This fight will proceed. Von Karma, you have a surprise round.")
        Phoenix().deskSlam.holdIt("Just because I'm investigating doesn't mean I've dropped my guard! I shouldn't be surprised!")
        Judge().eyesClosed.say("Ah, right. How to resolve this...")
        VonKarma().armsCrossed.say("Simple. My Sleight of Hand check needs to beat his passive Perception score. If it does, he's surprised.")
        Judge().positive.say("Very well. Make your Sleight of Hand check.")
        VonKarma().snapFinger.say(shakeSmall)
        Phoenix().confident.say("Ha! Only a roll of 5! There's no way you'll beat my passive Perception of 24!")
        VonKarma().confident.holdIt("You forgot about my Reliable Talent feature! I treat this roll as a 10, and my total comes out to $shakeMedium 25!")
        Phoenix().damage.say(flashMedium)
        Judge().surprised.say("A minimum roll of 25? Why did I even ask? Very well, you may take your surprise round.")
        VonKarma().snapFinger.say("Perfect! With my Assassinate feature, I get advantage, so that's ${pause(1.seconds)} a $shakeBig 23 to hit! And because you're surprised, it's an automatic critical hit!")
        Phoenix().breakdown.say("Gah! I don't have enough hit points to survive this! I'm toast!")
        Maya().determined.say("No, Phoenix, don't give up! There's no way he can defeat you in a single surprise round!")
        Phoenix().thinking.say("(Wait, surprise round... Of course!)")
        Phoenix().deskSlam.objection("There's no such thing as a surprise round!")
        Judge().surprised.say("What? Of course there's a surprise round, you were surprised!")
        Phoenix().read.say("No, not if we check the Combat Step by Step section on the first page of Chapter 9: Combat!")
            .say("There are no surprise rounds, only surprised creatures, who can't take actions or reactions while surprised.")
        Phoenix().deskSlam.say("Before the first turn of combat, ${pause(100.milliseconds)} we all roll initiative! ${pause(200.milliseconds)}And if my roll is higher, I'm not surprised during the attack!")
        VonKarma().damage.say(flashMedium)
        VonKarma().armsCrossed.say("Fine, but you're wasting our time if you think you can beat a rogue's initiative roll!")
        Judge().surprised.say("Oh, of course! Everyone, roll initiative!")
        VonKarma().snapFinger.say("18!")
        Maya().dull.say("Oh, no, I got a 3!")
        Maya().determined.say("But Polly got a 21!")
        Phoenix().stand.say("I got a roll of 10.")
        VonKarma().snapFinger.say("Ha, that's only a 13 for you!")
        Phoenix().confident.objection("You forget, as a Bard, I benefit from Jack of All Trades, which adds half of my proficiency bonus!")
        VonKarma().armsCrossed.say("Fine, but that's still only a 15.")
        Phoenix().headshake.say("That, and my Peerless Skill that lets me use a Bardic Inspiration to add a d12!")
        Phoenix().confident.say("And that's an additional +5, for a total of 20! I beat your initiative, and I'm no longer surprised")
        VonKarma().damage.say(flashMedium)
        VonKarma().cornered.say("Fine, so I lose the guaranteed critical hit, but I can still use Cunning Action: Aim!")
        VonKarma().armsCrossed.say("As long as I don't move, I get advantage on one attack roll, which ensures my sneak attack damage!")
        Phoenix().point.holdIt("Now that I'm not surprised, I can use Cutting Words as my reaction, subtracting a d12 roll from your attack roll! $shakeMedium ${pause(500.milliseconds)}")
        Phoenix().yell.say("That's a 9! Your attack roll is now 14, which is less than my Armor Class!")
        VonKarma().breakdown1.say("Fine, but you're still low on spells and hit points! You won't win this!")
        VonKarma().confident.say("You just used your two remaining Bardic Inspirations, you no longer have a chance!")
        Phoenix().thinking.say("(Great, now I can just hit him with hold person, and Maya and I will have enough time to take him out!)")
        Phoenix().cornered.say("(Or, I would, if Maya hadn't cast freedom of movement on him in the last fight!)")
        Judge().stand.say("Maya is also surprised, so after her we go to Phoenix at the top of the round!")
        Maya().stand.say("Wait, don't forget Polly! She got a 21!")
        VonKarma().stand.say("And what is a parrot supposed to do in this fight?")
        Phoenix().confident.say("She can use the Help action!")
        Maya().determined.say("Yeah, she'll do that!")
        VonKarma().stand.say("Fine, as if that'll accomplish anything.")
        Phoenix().confident.say("Oh, it will. On my turn, I cast plane shift!")
        VonKarma().confident.say("Ha! You're fleeing! Fine by me, I can eliminate Maya in peace, and then I'll come after you!")
        Phoenix().point.takeThat("I never said I was casting it on myself.")
        Phoenix().yell.say("I'm using it to target Von Karma!")
        VonKarma().snapFinger.say("To do that, you'll need to hit me with an attack roll!")
        Phoenix().nod.say("Yes, with advantage thanks to Polly! ${pause(1.seconds)} And that's a 21 to hit!")
        VonKarma().damage.say("Urgh! But I still get to make a Charisma saving throw!")
        VonKarma().snapFinger.say("17! That should be enough!")
        Phoenix().point.say("Nope, the DC is 18!")
        VonKarma().damage.say("$flashBig ${pause(1.seconds)}")
        VonKarma().breakdown1.say("Argh! Fine, I'll disappear for now, but I'll be back!")
        Judge().positive.say("Phoenix, which tuning fork did you use for this plane shift?")
        Phoenix().stand.say("The Elemental Plane of Fire.")
        VonKarma().armsCrossed.say("Very well. DM, I shall appear in the City of Brass! I'll use my contacts there to")
        Phoenix().read.objection("According to the PHB, the location in the new plane is determined randomly.")
        Judge().surprised.say("I see. I'll roll a d100...")
        Judge().negative.say("That's a 17. You appear in ${shakeBig}the Sea of Fire! ${pause(1.seconds)}You take 42 fire damage from the lava, and will continue to take 10d10 fire damage per round.")
        VonKarma().damage.say(flashBig)
        VonKarma().breakdown2.say("That's it, you're clearly all ganging up on me! I'm leaving, and not coming back!")
        Judge().negative.say("And good riddance!")
    }.writeTo("example.json")
}